


function hose_length_graphing(hose_length_sweep_simOut, hose_length_vector)

%plot length of hose against LH2 used
[hose_length_vector_output, LH2_consumed_warm_fill_output, ...
    LH2_in_AC_tank_warm_fill_output, frac_useful_LH2_warm_fill_output, ...
    LH2_consumed_cold_fill_output, LH2_in_AC_tank_cold_fill_output, ...
    frac_useful_LH2_cold_fill_output, time_warm_refuel_output, time_cold_refuel_output] = ...
    turn_simOut_into_graphing_data(hose_length_sweep_simOut, hose_length_vector);

    figure(101)
    plot(hose_length_vector_output, LH2_consumed_warm_fill_output)
    xlabel("Length of flexible hoses (m)")
    ylabel('LH2 consumed (kg)')
    title({"Total amount of LH2 consumed for warm tank", ...
        "refuel with different lengths of hoses"})
    saveas(gcf, 'Graphs/LH2 consumption for warm tank refuel sweep with 5-20m hoses.png')


hose_length_sweep_results = [hose_length_vector_output, LH2_consumed_warm_fill_output, ...
    LH2_in_AC_tank_warm_fill_output, frac_useful_LH2_warm_fill_output, ...
    LH2_consumed_cold_fill_output, LH2_in_AC_tank_cold_fill_output, ...
    frac_useful_LH2_cold_fill_output, time_warm_refuel_output, time_cold_refuel_output];
    
hose_length_results_table = array2table(hose_length_sweep_results, ...
    'VariableNames', {'Length of flexible hoses (m)' 'LH2 consumed warm tank refuel (kg)' ...
    'LH2 received warm tank refuel (kg)' 'Fraction of useful LH2 for warm tank refuel' ...
    'LH2 consumed cold tank refuel (kg)' 'LH2 received cold tank refuel (kg)' ...
    'Fraction of useful LH2 for cold tank refuel' 'Time taken for warm tank refuel (s)'...
    'Time taken for cold tank refuel (s)'});

writetable(hose_length_results_table, "Graphs/hose_length_sweep_results.xlsx")

end